# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CDU.py
# Created on: 2019-12-12 12:09:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/ferregutie/AppData/Roaming/ESRI/Desktop10.6/ArcToolbox/My Toolboxes/URBAN.tbx")


# Local variables:
Coordinate_catastali = ""
json = ""
poligono = ""
output_json = ""
output_testo_PI = ""
output_json__2_ = ""
output_testo_PAT = ""

# Process: da coordinate catastali a layertemporaneo
arcpy.gp.toolbox = "C:/Users/ferregutie/AppData/Roaming/ESRI/Desktop10.6/ArcToolbox/My Toolboxes/URBAN.tbx";
# Warning: the toolbox C:/Users/ferregutie/AppData/Roaming/ESRI/Desktop10.6/ArcToolbox/My Toolboxes/URBAN.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.coordinateCatastaliToLayer(...) with arcpy.coordinateCatastaliToLayer_ALIAS(...)
arcpy.gp.coordinateCatastaliToLayer(Coordinate_catastali)

# Process: CDU_PI
arcpy.gp.toolbox = "C:/Users/ferregutie/AppData/Roaming/ESRI/Desktop10.6/ArcToolbox/My Toolboxes/URBAN.tbx";
# Warning: the toolbox C:/Users/ferregutie/AppData/Roaming/ESRI/Desktop10.6/ArcToolbox/My Toolboxes/URBAN.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.CDUPI(...) with arcpy.CDUPI_ALIAS(...)
arcpy.gp.CDUPI(poligono, output_json)

# Process: CDU_PAT
arcpy.gp.toolbox = "C:/Users/ferregutie/AppData/Roaming/ESRI/Desktop10.6/ArcToolbox/My Toolboxes/URBAN.tbx";
# Warning: the toolbox C:/Users/ferregutie/AppData/Roaming/ESRI/Desktop10.6/ArcToolbox/My Toolboxes/URBAN.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.CDUPAT(...) with arcpy.CDUPAT_ALIAS(...)
arcpy.gp.CDUPAT(poligono, output_json__2_)

